spring:
  application:
    name: ai-agent
  ai:
    dashscope:
      api-key: sk-8bf76e45372c4ab38c67fb16f4018050
      chat:
        options:
          model: qwen-plus
    ollama:
      base-url: http://localhost:11434
      chat:
        model: gemma3:1b
    chat:
      observation:
        enabled: false
logging:
  level:
    org.springframework.ai.chat.client.advisor.SimpleLoggerAdvisor: debug
server:
  port: 8101
  servlet:
    context-path: /api

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.mashang.web.controller
app:
  chat-memory:
    dir: ./chat-memory  # 对话记忆存储目录

knife4j:
  enable: true
  setting:
    language: zh_cn